agents:
  queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"

steps:
  - name: ":construction: Build the app"
    key: "build"
    artifact_paths:
      - "target/*"
    plugins:
      - docker-compose#v3.10.0:
          config: docker-compose.build.yml
          run: build

  - name: ":shipit: Publish docker image"
    key: "publish"
    depends_on: "build"
    command: "scripts/publish.sh"
